## Travis CI configuration for the cookiecutter-python-app project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-python-app>
##
language: python

# This will fail for Python 3.4+ on Travis Ubuntu workers. The problem seems to
# be Ubuntu's crippled Python 3, which is made worse with Travis. The Python 3
# version of the test script relies on the now-standard pip command and venv
# module, but these are missing from the default Ubuntu Python installation.

python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - master
    - dev

sudo: false

install:
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  - python tests/test_template.py
