## Travis CI configuration for the cookiecutter-python-app project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-python-app>
##
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

branches:
  only:
    - master 
    - dev

sudo: false

script:
  - python tests/test_template.py
