## Travis CI configuration for the cookiecutter-python-app project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-python-app>
##
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - master 
    - dev

sudo: false

install:
  - python -m pip install --requirement=requirements.txt --requirement=tests/requirements.txt

script:
  - python tests/test_template.py
